# clone:
#   git:
#     image: woodpecker/plugin-git
#     settings:
#       skip-verify: true
pipeline:
  test:
    image: alpine
    commands:
      - echo "Woodpecker CI is working!"
      - ls
  build:
    image: docker:19.03.12
    commands:
      - systemctl start docker
      - docker build -t test:latest .
