# when:
#   - branch: master
#     event: [push, deployment]
#   - event: tag
# # clone:
# #   git:
# #     image: woodpecker/plugin-git
# #     settings:
# #       skip-verify: true
# steps:
#   - name: build-image
#     image: docker
#     commands:
#       - docker build --rm -t local/woodpecker-test .
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock 


pipeline:
 steps:
    - name: build
      image: 'docker:19.03.12'
      commands:
        - docker build -t priya20xenonstack/woodpecker-test:latest -f Dockerfile .
        - docker login -u $docker_username -p $docker_password
        - docker push priya20xenonstack/woodpecker-test:latest
      when:
        event: tag
      secrets:
        - 'docker_username'
        - 'docker_password'

